pipeline:
  build:
    image: ldangelo/elixir-phoenix
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile
      - mix release --env=prod
  
