workspace:
  base: /socialshare
  path: src
  
pipeline:
  build:
    image: ldangelo/elixir-phoenix:1.0
    commands:
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile
      - mix release --env=prod
  
