# Dockerfile.build
FROM bitwalker/alpine-elixir-phoenix
ENV HOME=/opt/app/ TERM=xterm

# Install Hex+Rebar
RUN mix local.hex --force && \
mix local.rebar --force
WORKDIR /opt/app
#RUN cargo update
ENV MIX_ENV=prod REPLACE_OS_VARS=true
# Cache elixir deps
COPY mix.exs mix.lock ./
RUN mix deps.get
COPY config ./config
RUN mix deps.compile
COPY . .
RUN mix release --env=prod
