resources:
  - name: resource-socialshare
    type: git
    source:
      uri: https://github.com/ldangelo/socialshare.git
      branch: master

jobs:
  - name: job-build
    serial: true
    plan:
      - get: resource-socialshare
      - task: mix-build
        file: resource-socialshare/pipeline/mix-build.yml
