resources:
  - name: socialshare
    type: git
    source:
      uri: https://github.com/ldangelo/socialshare.git
      branch: ((branch-name))
#  - name: socialshare-docker-((build-env))
#    type: dockerimage
#    source:
#      repository: busybox
#      username: ((dockerhub-username))
#      password: ((dockerhub-password))
  - name: socialshare-docker-((build-env))
    type: docker-image
    source:
      repository: ((dockerhub-username))/socialshare-((build-env))
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: get-source
    public: false
    serial: true
    plan:
      - get: socialshare
        trigger: true

  - name: update-dependencies
    public: false
    serial: true
    plan:
      - task: update-dependencies
        file: socialshare/pipeline/update-dependencies.yml

  - name: build-test
    public: false
    serial: false
    plan:
      - aggregate:
          - task: mix-build
            file: socialshare/pipeline/mix-build.yml
          - task: test
            file: socialshare/pipeline/test.yml

  - name: publish
    public: false
    serial: false
    plan:
      - put: socialshare-docker-((build-env))
        params:
          inputs: app
          build: socialshare/docker
