resources:
  - name: socialshare
    type: git
    source:
      uri: https://github.com/ldangelo/socialshare.git
      branch: ((branch-name))
#  - name: elixir-phoenix
#    type: dockerimage
#    source:
#      repository: ((dockerhub-username))/elixir-phoenix
#      tag: "1.0"
#      username: ((dockerhub-username))
#      password: ((dockerhub-password))
  - name: socialshare-docker-((build-env))
    type: dockerimage
    source:
      repository: ((dockerhub-username))/socialshare
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: build
    public: false
    serial: true
    plan:
      - get: socialshare
        trigger: true
      - task: mix-build
        file: socialshare/pipeline/mix-build.yml
      - task: create-context
        file: socialshare/pipeline/create-context.yml
      - put: socialshare-docker-((build-env))
        params:
          build: context
