resources:
  - name: socialshare
    type: git
    source:
      uri: https://github.com/ldangelo/socialshare.git
      branch: ((branch-name))
  - name: socialshare-docker-((build-env))
    type: dockerimage
    source:
      repository: ((dockerhub-username))/socialshare
      username: ((dockerhub-username))
      password: ((dockerhub-password))

jobs:
  - name: build
    public: false
    serial: true
    plan:
      - get: socialshare
        trigger: true
      - task: mix-build
        file: pipeline/mix-build.yml
      - task: create-context
        file: pipeline/create-context.yml
      - put: socialshare-docker-dev
        params:
          build: context
